<a href="https://colab.research.google.com/github/Sonuthahreen/DAY-2/blob/main/DAY2_Getting_information_from_tensors%2Cmatrix_opeartions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Getting information from tensor**(tensor attributes)

1.Tensors not right datatype -to do get datatype from a tensor,can use tensor.dtype

2.tensors not right shape-to get shape from a tensor,can use tensor.shape

3.Tensor not on the right device-to get device shape from tensor,can use tensor.device

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


In [5]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8592, 0.2398, 0.0873, 0.9941],
        [0.3188, 0.4095, 0.9265, 0.7199],
        [0.2323, 0.0439, 0.5783, 0.4559]])

In [6]:
#finding out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.8592, 0.2398, 0.0873, 0.9941],
        [0.3188, 0.4095, 0.9265, 0.7199],
        [0.2323, 0.0439, 0.5783, 0.4559]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


In [7]:
#create a tensor(practice)
some_tensor=torch.rand(5,10)
some_tensor

tensor([[0.2226, 0.9934, 0.2313, 0.6575, 0.2601, 0.2400, 0.3337, 0.3166, 0.0698,
         0.7305],
        [0.0509, 0.0956, 0.7804, 0.5133, 0.6988, 0.1995, 0.7070, 0.6417, 0.4088,
         0.2033],
        [0.3984, 0.3495, 0.5929, 0.6574, 0.3948, 0.2000, 0.4791, 0.7696, 0.4802,
         0.2802],
        [0.5411, 0.6686, 0.3441, 0.5276, 0.3296, 0.9996, 0.4329, 0.0467, 0.0018,
         0.0258],
        [0.1904, 0.0714, 0.7508, 0.5604, 0.4126, 0.3048, 0.9245, 0.7356, 0.3667,
         0.0380]])

In [8]:
#finding out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.2226, 0.9934, 0.2313, 0.6575, 0.2601, 0.2400, 0.3337, 0.3166, 0.0698,
         0.7305],
        [0.0509, 0.0956, 0.7804, 0.5133, 0.6988, 0.1995, 0.7070, 0.6417, 0.4088,
         0.2033],
        [0.3984, 0.3495, 0.5929, 0.6574, 0.3948, 0.2000, 0.4791, 0.7696, 0.4802,
         0.2802],
        [0.5411, 0.6686, 0.3441, 0.5276, 0.3296, 0.9996, 0.4329, 0.0467, 0.0018,
         0.0258],
        [0.1904, 0.0714, 0.7508, 0.5604, 0.4126, 0.3048, 0.9245, 0.7356, 0.3667,
         0.0380]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([5, 10])
Device tensor is on:cpu


**MANUPULATING TENSORS**

Tensor Operations:
-additions

-subtraction

-multiplication(element-wise)

-division

-matrix multiplications

In [16]:
#performing addition operations
#create tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [13]:
#performing multipiliction operation
tensor=torch.tensor([1,2,3])
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [14]:
#performing subtraction operation
tensor=torch.tensor([1,2,3])
tensor=tensor-10
tensor

tensor([-9, -8, -7])

In [19]:
#PYTORCH IN-BUILT FUCTIONS
torch.mul(tensor,10)


tensor([10, 20, 30])

In [20]:
torch.add(tensor,10)

tensor([11, 12, 13])

**MATRIX MULTIPLICATION**

-Two main ways of performing multiplication in neural networks and deep learning:

1.Element-Wise multiplication

2.matrix mutltiplication is also refered to dot product(a.b)


In [21]:
#Element-Wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [22]:
#matrix multiplication
torch.matmul(tensor,tensor)
#why we got 14 means each vale is multiplied by anthor value

tensor(14)

In [29]:
tensor

tensor([1, 2, 3])

In [27]:
#matrix multiplication done in this way
1*1+2*2+3*3

14

In [34]:
%%time
value=0
for i in range (len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor(14)
CPU times: user 978 µs, sys: 1.01 ms, total: 1.98 ms
Wall time: 1.84 ms


In [35]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 91 µs, sys: 0 ns, total: 91 µs
Wall time: 95.8 µs


tensor(14)

The are two main rules that erforming matrix multiplication need to satisfy:

1.inner demensions must  be match:

* '(3,2) @ (3,2)' wont work
* (2,3) @ (3,2)   work
* (3,2) @(2,3) work

2.the resulting matrix has the shape of the outer dimensions:

* '(2,3) @ (3,2) ->(2,2)

* '(3,2) @ (2,3) ->(3,3)


In [36]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.1262, 0.4392],
        [0.7678, 0.6454]])

In [39]:
torch.matmul(torch.rand(10,2),torch.rand(2,10))

tensor([[0.7548, 1.3718, 0.7968, 0.4946, 0.7970, 0.9437, 0.4329, 0.4297, 0.4340,
         0.6452],
        [0.4405, 0.7737, 0.4032, 0.2320, 0.5555, 0.5248, 0.2247, 0.1969, 0.2348,
         0.3297],
        [0.6438, 1.1332, 0.5950, 0.3444, 0.8035, 0.7694, 0.3310, 0.2928, 0.3448,
         0.4863],
        [0.4330, 0.7685, 0.4147, 0.2449, 0.5191, 0.5236, 0.2292, 0.2096, 0.2363,
         0.3381],
        [0.0807, 0.1587, 0.1128, 0.0781, 0.0449, 0.1125, 0.0588, 0.0699, 0.0547,
         0.0899],
        [0.7226, 1.3442, 0.8336, 0.5383, 0.6595, 0.9332, 0.4465, 0.4730, 0.4367,
         0.6713],
        [0.2604, 0.5100, 0.3591, 0.2478, 0.1519, 0.3609, 0.1874, 0.2216, 0.1750,
         0.2863],
        [0.7263, 1.3497, 0.8349, 0.5384, 0.6671, 0.9367, 0.4474, 0.4728, 0.4381,
         0.6725],
        [0.1069, 0.1906, 0.1045, 0.0624, 0.1250, 0.1301, 0.0575, 0.0536, 0.0590,
         0.0851],
        [0.4672, 0.8349, 0.4608, 0.2765, 0.5406, 0.5705, 0.2533, 0.2378, 0.2589,
         0.3748]])

**one of the most common errors in deep learning(DL)** that are shape errors

In [40]:
#shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],[3,4],[4,5]])
tensor_B=torch.tensor([[6,7],[8,9],[10,11]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_B.T

tensor([[ 6,  8, 10],
        [ 7,  9, 11]])

In [41]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues we can manupilate the shape of one of our tensors using TRANSPOSE. a TANSPOSE switces the axes or dimension of a given tensor

In [42]:
tensor_B,tensor_B.shape

(tensor([[ 6,  7],
         [ 8,  9],
         [10, 11]]),
 torch.Size([3, 2]))

In [43]:
tensor_B.T,tensor_B.T.shape
##T-transpose

(tensor([[ 6,  8, 10],
         [ 7,  9, 11]]),
 torch.Size([2, 3]))

In [46]:
#the matrix multiplication operation workss when tensor_B is transposed
print(f"original shapes: tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"new shape:tensor_A={tensor_A.shape}(same shape as above),tensor_B.T={tensor_B.T.shape}")
print(f"multiplying:{tensor_A.shape} @ {tensor_B.T.shape}<-inner dimension must match")
print("output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape:{output.shape}")

original shapes: tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
new shape:tensor_A=torch.Size([3, 2])(same shape as above),tensor_B.T=torch.Size([2, 3])
multiplying:torch.Size([3, 2]) @ torch.Size([2, 3])<-inner dimension must match
output:

tensor([[20, 26, 32],
        [46, 60, 74],
        [59, 77, 95]])

output shape:torch.Size([3, 3])


In [47]:
#practice
#the matrix multiplication operation workss when tensor_B is transposed
print(f"original shapes: tensor_B={tensor_A.shape},tensor_A={tensor_B.shape}")
print(f"new shape:tensor_B={tensor_B.shape}(same shape as above),tensor_A.T={tensor_A.T.shape}")
print(f"multiplying:{tensor_B.shape} @ {tensor_A.T.shape}<-inner dimension must match")
print("output:\n")
output=torch.matmul(tensor_B,tensor_A.T)
print(output)
print(f"\noutput shape:{output.shape}")

original shapes: tensor_B=torch.Size([3, 2]),tensor_A=torch.Size([3, 2])
new shape:tensor_B=torch.Size([3, 2])(same shape as above),tensor_A.T=torch.Size([2, 3])
multiplying:torch.Size([3, 2]) @ torch.Size([2, 3])<-inner dimension must match
output:

tensor([[20, 46, 59],
        [26, 60, 77],
        [32, 74, 95]])

output shape:torch.Size([3, 3])


Finding the MIN,MAX,MEAN,SUm(tensor aggregation)

In [53]:
#create a tensor
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [54]:
#find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [55]:
#find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [59]:
#find the mean
#Note:the torch mean() function reqquires a tensor datatype32 to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [60]:
#find sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
##finding the positional min and max

In [61]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
#finding the position in tensor that as min value with argmin()-> reurns index position of target tensor where the min value occur
x.argmin()

tensor(0)

In [63]:
x[0]

tensor(0)

In [64]:
#finding the position in tensor that as max value with argmax()

x.argmax()

tensor(9)

In [65]:
x[9]

tensor(90)

In [66]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])